name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Maven
        if: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: mvn --batch-mode --update-snapshots verify
      - name: Deploy to Package Registry
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
